// Legal content — all 12 languages.
// English is the source of truth.

const privacy = {
  en: {
    title: "Privacy Policy",
    lastUpdated: "April 2026",
    sections: [
      { heading: "Introduction", body: "MovesBook is a personal breaking training app. Your privacy matters to us. This policy explains what data we collect, how we store it, and your rights." },
      { heading: "Data We Collect", body: "We collect only the data you enter into the app: moves, sets, goals, habits, notes, battle plans, sparring sessions, calendar entries, profile information (nickname, age, breaking start date), and app settings.\n\nWe do not collect analytics, browsing history, location data, or any data beyond what you explicitly enter." },
      { heading: "How Data Is Stored", body: "All data is stored locally on your device using browser localStorage. This data never leaves your device unless you choose to sign in.\n\nIf you sign in with Google or Email, your data is synced to Google Firebase Firestore for cloud backup and cross-device access. Firebase is operated by Google and subject to Google's security standards." },
      { heading: "Authentication", body: "We use Firebase Authentication (Google sign-in and email/password). We do not store your password. Authentication tokens are managed by Firebase." },
      { heading: "Third-Party Services", body: "MovesBook uses the following third-party services:\n• Firebase Authentication — for sign-in\n• Firebase Firestore — for cloud data sync\n• EmailJS — for sending feedback messages (only when you use the feedback form)\n• Vercel — for hosting the web application\n\nNo advertising networks, analytics trackers, or social media pixels are used." },
      { heading: "Data Sharing", body: "We do not sell, share, or transfer your data to any third party. Your training data is yours alone.\n\nThe only exception is data you explicitly choose to share yourself, such as shareable cards or exported spar sessions." },
      { heading: "Data Retention", body: "Local data persists as long as you keep it in your browser. Cloud data persists as long as your account exists. You can delete your data at any time using the app's backup/restore features or by clearing browser storage." },
      { heading: "Your Rights", body: "You have the right to:\n• Access all your data (use the Backup feature to export)\n• Delete your data (clear localStorage or delete your account)\n• Use the app without signing in (offline-only mode)\n• Opt out of cloud sync at any time by signing out" },
      { heading: "Children's Privacy", body: "MovesBook does not knowingly collect data from children under 13. If you are under 13, please use the app in offline mode without creating an account." },
      { heading: "Changes to This Policy", body: "We may update this policy occasionally. Changes will be reflected in the 'Last updated' date. Continued use of the app after changes constitutes acceptance." },
      { heading: "Contact", body: "For privacy questions, use the Feedback form in the app or contact us through the app's support channels." },
    ]
  },
  it: {
    title: "Informativa sulla Privacy",
    lastUpdated: "Aprile 2026",
    sections: [
      { heading: "Introduzione", body: "MovesBook è un'app di allenamento personale per breaking. La tua privacy è importante per noi. Questa informativa spiega quali dati raccogliamo, come li conserviamo e i tuoi diritti." },
      { heading: "Dati che Raccogliamo", body: "Raccogliamo solo i dati che inserisci nell'app: mosse, set, obiettivi, abitudini, note, piani di battle, sessioni di sparring, voci del calendario, informazioni del profilo (soprannome, età, data di inizio breaking) e impostazioni dell'app.\n\nNon raccogliamo analitiche, cronologia di navigazione, dati di posizione o dati oltre a ciò che inserisci esplicitamente." },
      { heading: "Come Vengono Conservati i Dati", body: "Tutti i dati sono conservati localmente sul tuo dispositivo usando il localStorage del browser. Questi dati non lasciano mai il tuo dispositivo a meno che tu non scelga di accedere.\n\nSe accedi con Google o Email, i tuoi dati vengono sincronizzati su Google Firebase Firestore per backup cloud e accesso multi-dispositivo." },
      { heading: "Autenticazione", body: "Utilizziamo Firebase Authentication (accesso Google e email/password). Non conserviamo la tua password. I token di autenticazione sono gestiti da Firebase." },
      { heading: "Servizi di Terze Parti", body: "MovesBook utilizza i seguenti servizi di terze parti:\n• Firebase Authentication — per l'accesso\n• Firebase Firestore — per la sincronizzazione cloud dei dati\n• EmailJS — per l'invio di messaggi di feedback\n• Vercel — per l'hosting dell'applicazione web\n\nNon vengono utilizzate reti pubblicitarie, tracker analitici o pixel di social media." },
      { heading: "Condivisione dei Dati", body: "Non vendiamo, condividiamo o trasferiamo i tuoi dati a terze parti. I tuoi dati di allenamento sono solo tuoi.\n\nL'unica eccezione sono i dati che scegli esplicitamente di condividere, come carte condivisibili o sessioni di spar esportate." },
      { heading: "Conservazione dei Dati", body: "I dati locali persistono finché li mantieni nel browser. I dati cloud persistono finché il tuo account esiste. Puoi eliminare i tuoi dati in qualsiasi momento." },
      { heading: "I Tuoi Diritti", body: "Hai il diritto di:\n• Accedere a tutti i tuoi dati (usa la funzione Backup per esportare)\n• Eliminare i tuoi dati (cancella localStorage o elimina il tuo account)\n• Usare l'app senza accedere (modalità solo offline)\n• Disattivare la sincronizzazione cloud in qualsiasi momento disconnettendoti" },
      { heading: "Privacy dei Minori", body: "MovesBook non raccoglie consapevolmente dati da minori di 13 anni. Se hai meno di 13 anni, usa l'app in modalità offline senza creare un account." },
      { heading: "Modifiche a Questa Informativa", body: "Potremmo aggiornare questa informativa occasionalmente. Le modifiche saranno riflesse nella data 'Ultimo aggiornamento'." },
      { heading: "Contatto", body: "Per domande sulla privacy, usa il modulo Feedback nell'app o contattaci attraverso i canali di supporto dell'app." },
    ]
  },
  es: {
    title: "Política de Privacidad",
    lastUpdated: "Abril 2026",
    sections: [
      { heading: "Introducción", body: "MovesBook es una aplicación de entrenamiento personal de breaking. Tu privacidad es importante para nosotros. Esta política explica qué datos recopilamos, cómo los almacenamos y tus derechos." },
      { heading: "Datos que Recopilamos", body: "Solo recopilamos los datos que introduces en la app: movimientos, sets, objetivos, hábitos, notas, planes de batalla, sesiones de sparring, entradas de calendario, información de perfil y configuraciones.\n\nNo recopilamos analíticas, historial de navegación, datos de ubicación ni datos más allá de lo que introduces explícitamente." },
      { heading: "Cómo se Almacenan los Datos", body: "Todos los datos se almacenan localmente en tu dispositivo usando localStorage del navegador. Estos datos nunca salen de tu dispositivo a menos que elijas iniciar sesión.\n\nSi inicias sesión con Google o Email, tus datos se sincronizan con Google Firebase Firestore para respaldo en la nube y acceso multi-dispositivo." },
      { heading: "Autenticación", body: "Usamos Firebase Authentication (inicio de sesión con Google y email/contraseña). No almacenamos tu contraseña. Los tokens de autenticación son gestionados por Firebase." },
      { heading: "Servicios de Terceros", body: "MovesBook usa los siguientes servicios de terceros:\n• Firebase Authentication — para inicio de sesión\n• Firebase Firestore — para sincronización de datos en la nube\n• EmailJS — para enviar mensajes de feedback\n• Vercel — para hosting de la aplicación web\n\nNo se usan redes publicitarias, rastreadores analíticos ni píxeles de redes sociales." },
      { heading: "Compartir Datos", body: "No vendemos, compartimos ni transferimos tus datos a terceros. Tus datos de entrenamiento son solo tuyos." },
      { heading: "Retención de Datos", body: "Los datos locales persisten mientras los mantengas en tu navegador. Los datos en la nube persisten mientras tu cuenta exista. Puedes eliminar tus datos en cualquier momento." },
      { heading: "Tus Derechos", body: "Tienes derecho a:\n• Acceder a todos tus datos (usa la función de Respaldo)\n• Eliminar tus datos (limpia localStorage o elimina tu cuenta)\n• Usar la app sin iniciar sesión (modo solo offline)\n• Desactivar la sincronización en la nube cerrando sesión" },
      { heading: "Privacidad de Menores", body: "MovesBook no recopila conscientemente datos de menores de 13 años. Si tienes menos de 13 años, usa la app en modo offline sin crear una cuenta." },
      { heading: "Cambios a Esta Política", body: "Podemos actualizar esta política ocasionalmente. Los cambios se reflejarán en la fecha 'Última actualización'." },
      { heading: "Contacto", body: "Para preguntas sobre privacidad, usa el formulario de Feedback en la app." },
    ]
  },
  fr: {
    title: "Politique de Confidentialité",
    lastUpdated: "Avril 2026",
    sections: [
      { heading: "Introduction", body: "MovesBook est une application d'entraînement personnel de breaking. Votre vie privée nous importe. Cette politique explique quelles données nous collectons, comment nous les stockons et vos droits." },
      { heading: "Données Collectées", body: "Nous collectons uniquement les données que vous entrez dans l'application : mouvements, sets, objectifs, habitudes, notes, plans de battle, sessions de sparring, entrées de calendrier, informations de profil et paramètres.\n\nNous ne collectons pas d'analytiques, d'historique de navigation, de données de localisation ni de données au-delà de ce que vous entrez explicitement." },
      { heading: "Stockage des Données", body: "Toutes les données sont stockées localement sur votre appareil via le localStorage du navigateur. Ces données ne quittent jamais votre appareil sauf si vous choisissez de vous connecter.\n\nSi vous vous connectez avec Google ou Email, vos données sont synchronisées avec Google Firebase Firestore." },
      { heading: "Authentification", body: "Nous utilisons Firebase Authentication (connexion Google et email/mot de passe). Nous ne stockons pas votre mot de passe." },
      { heading: "Services Tiers", body: "MovesBook utilise les services tiers suivants :\n• Firebase Authentication — pour la connexion\n• Firebase Firestore — pour la synchronisation cloud\n• EmailJS — pour l'envoi de messages de feedback\n• Vercel — pour l'hébergement\n\nAucun réseau publicitaire, tracker analytique ou pixel de média social n'est utilisé." },
      { heading: "Partage des Données", body: "Nous ne vendons, partageons ni transférons vos données à des tiers. Vos données d'entraînement sont les vôtres uniquement." },
      { heading: "Conservation des Données", body: "Les données locales persistent tant que vous les gardez dans votre navigateur. Les données cloud persistent tant que votre compte existe." },
      { heading: "Vos Droits", body: "Vous avez le droit de :\n• Accéder à toutes vos données (utilisez la fonction Sauvegarde)\n• Supprimer vos données\n• Utiliser l'application sans connexion (mode hors ligne)\n• Désactiver la synchronisation cloud en vous déconnectant" },
      { heading: "Vie Privée des Mineurs", body: "MovesBook ne collecte pas sciemment de données de mineurs de moins de 13 ans." },
      { heading: "Modifications", body: "Nous pouvons mettre à jour cette politique occasionnellement. Les changements seront reflétés dans la date de mise à jour." },
      { heading: "Contact", body: "Pour toute question sur la confidentialité, utilisez le formulaire de Feedback dans l'application." },
    ]
  },
  pt: { title:"Política de Privacidade", lastUpdated:"Abril 2026", sections:[
    { heading:"Introdução", body:"MovesBook é um app de treino pessoal de breaking. Sua privacidade é importante para nós. Esta política explica quais dados coletamos, como os armazenamos e seus direitos." },
    { heading:"Dados que Coletamos", body:"Coletamos apenas os dados que você insere no app: movimentos, sets, objetivos, hábitos, notas, planos de battle, sessões de spar, entradas de calendário, informações de perfil e configurações.\n\nNão coletamos analytics, histórico de navegação, dados de localização ou dados além do que você insere explicitamente." },
    { heading:"Armazenamento de Dados", body:"Todos os dados são armazenados localmente no seu dispositivo usando localStorage do navegador. Se você fizer login, os dados são sincronizados com Google Firebase Firestore." },
    { heading:"Autenticação", body:"Usamos Firebase Authentication (login Google e email/senha). Não armazenamos sua senha." },
    { heading:"Serviços de Terceiros", body:"MovesBook usa: Firebase Authentication, Firebase Firestore, EmailJS e Vercel. Nenhuma rede de publicidade ou tracker é utilizado." },
    { heading:"Compartilhamento", body:"Não vendemos, compartilhamos ou transferimos seus dados a terceiros." },
    { heading:"Retenção", body:"Dados locais persistem enquanto mantidos no navegador. Dados na nuvem persistem enquanto sua conta existir." },
    { heading:"Seus Direitos", body:"Você tem o direito de acessar, exportar e deletar todos os seus dados a qualquer momento." },
    { heading:"Privacidade de Menores", body:"MovesBook não coleta conscientemente dados de menores de 13 anos." },
    { heading:"Alterações", body:"Podemos atualizar esta política ocasionalmente. Mudanças serão refletidas na data de atualização." },
    { heading:"Contato", body:"Para questões de privacidade, use o formulário de Feedback no app." },
  ]},
  de: { title:"Datenschutzrichtlinie", lastUpdated:"April 2026", sections:[
    { heading:"Einleitung", body:"MovesBook ist eine persönliche Breaking-Trainings-App. Ihre Privatsphäre ist uns wichtig. Diese Richtlinie erklärt, welche Daten wir erheben, wie wir sie speichern und Ihre Rechte." },
    { heading:"Erhobene Daten", body:"Wir erheben nur Daten, die Sie in die App eingeben: Moves, Sets, Ziele, Gewohnheiten, Notizen, Battle-Pläne, Sparring-Sitzungen, Kalendereinträge, Profilinformationen und Einstellungen.\n\nWir erheben keine Analysen, Browserverlauf, Standortdaten oder sonstige Daten." },
    { heading:"Datenspeicherung", body:"Alle Daten werden lokal auf Ihrem Gerät im Browser-localStorage gespeichert. Bei Anmeldung werden Daten mit Google Firebase Firestore synchronisiert." },
    { heading:"Authentifizierung", body:"Wir verwenden Firebase Authentication (Google und E-Mail/Passwort). Wir speichern Ihr Passwort nicht." },
    { heading:"Drittanbieter", body:"MovesBook nutzt: Firebase Authentication, Firebase Firestore, EmailJS und Vercel. Keine Werbenetzwerke oder Tracker werden verwendet." },
    { heading:"Datenweitergabe", body:"Wir verkaufen, teilen oder übertragen Ihre Daten nicht an Dritte." },
    { heading:"Datenspeicherung", body:"Lokale Daten bleiben bestehen, solange Sie sie im Browser behalten. Cloud-Daten bleiben bestehen, solange Ihr Konto existiert." },
    { heading:"Ihre Rechte", body:"Sie haben das Recht, alle Ihre Daten jederzeit einzusehen, zu exportieren und zu löschen." },
    { heading:"Datenschutz für Minderjährige", body:"MovesBook erhebt wissentlich keine Daten von Kindern unter 13 Jahren." },
    { heading:"Änderungen", body:"Wir können diese Richtlinie gelegentlich aktualisieren. Änderungen werden im Aktualisierungsdatum reflektiert." },
    { heading:"Kontakt", body:"Für Datenschutzfragen nutzen Sie das Feedback-Formular in der App." },
  ]},
  ja: { title:"プライバシーポリシー", lastUpdated:"2026年4月", sections:[
    { heading:"はじめに", body:"MovesBookはブレイキンの個人トレーニングアプリです。あなたのプライバシーは重要です。このポリシーでは、収集するデータ、保存方法、およびあなたの権利について説明します。" },
    { heading:"収集するデータ", body:"アプリに入力したデータのみを収集します：ムーブ、セット、目標、習慣、ノート、バトルプラン、スパーリングセッション、カレンダーエントリ、プロフィール情報、設定。\n\nアナリティクス、閲覧履歴、位置情報、その他のデータは収集しません。" },
    { heading:"データの保存方法", body:"すべてのデータはブラウザのlocalStorageを使用してデバイスにローカル保存されます。サインインするとGoogle Firebase Firestoreに同期されます。" },
    { heading:"認証", body:"Firebase Authentication（GoogleサインインとEメール/パスワード）を使用しています。パスワードは保存しません。" },
    { heading:"サードパーティサービス", body:"MovesBookは以下を使用：Firebase Authentication、Firebase Firestore、EmailJS、Vercel。広告ネットワークやトラッカーは使用していません。" },
    { heading:"データ共有", body:"データを第三者に販売、共有、転送することはありません。" },
    { heading:"データ保持", body:"ローカルデータはブラウザに保持される限り存続します。クラウドデータはアカウントが存在する限り存続します。" },
    { heading:"あなたの権利", body:"すべてのデータにアクセス、エクスポート、削除する権利があります。" },
    { heading:"未成年者のプライバシー", body:"MovesBookは13歳未満の子供からデータを故意に収集しません。" },
    { heading:"ポリシーの変更", body:"このポリシーを随時更新する場合があります。変更は更新日に反映されます。" },
    { heading:"お問い合わせ", body:"プライバシーに関するご質問は、アプリ内のフィードバックフォームをご利用ください。" },
  ]},
  zh: { title:"隐私政策", lastUpdated:"2026年4月", sections:[
    { heading:"简介", body:"MovesBook是一款个人Breaking训练应用。我们重视您的隐私。本政策说明我们收集哪些数据、如何存储以及您的权利。" },
    { heading:"我们收集的数据", body:"我们仅收集您在应用中输入的数据：动作、套路、目标、习惯、笔记、Battle计划、Spar会话、日历条目、个人资料信息和设置。\n\n我们不收集分析数据、浏览历史、位置数据或任何其他数据。" },
    { heading:"数据存储方式", body:"所有数据使用浏览器localStorage存储在您的设备本地。登录后，数据会同步到Google Firebase Firestore。" },
    { heading:"身份验证", body:"我们使用Firebase Authentication（Google登录和电子邮件/密码）。我们不存储您的密码。" },
    { heading:"第三方服务", body:"MovesBook使用：Firebase Authentication、Firebase Firestore、EmailJS和Vercel。不使用广告网络或追踪器。" },
    { heading:"数据共享", body:"我们不会向任何第三方出售、共享或转移您的数据。" },
    { heading:"数据保留", body:"本地数据在浏览器中保留期间持续存在。云数据在账户存在期间持续存在。" },
    { heading:"您的权利", body:"您有权随时访问、导出和删除所有数据。" },
    { heading:"未成年人隐私", body:"MovesBook不会故意收集13岁以下儿童的数据。" },
    { heading:"政策变更", body:"我们可能会偶尔更新本政策。变更将反映在更新日期中。" },
    { heading:"联系方式", body:"如有隐私问题，请使用应用内的反馈表单。" },
  ]},
  ru: { title:"Политика конфиденциальности", lastUpdated:"Апрель 2026", sections:[
    { heading:"Введение", body:"MovesBook — приложение для персональных тренировок по брейкингу. Ваша конфиденциальность важна для нас. Эта политика объясняет, какие данные мы собираем, как храним и ваши права." },
    { heading:"Собираемые данные", body:"Мы собираем только данные, которые вы вводите в приложение: движения, сеты, цели, привычки, заметки, планы батлов, спарринг-сессии, записи календаря, информацию профиля и настройки.\n\nМы не собираем аналитику, историю браузера, данные о местоположении или другие данные." },
    { heading:"Хранение данных", body:"Все данные хранятся локально на вашем устройстве в localStorage браузера. При входе данные синхронизируются с Google Firebase Firestore." },
    { heading:"Аутентификация", body:"Мы используем Firebase Authentication (вход через Google и email/пароль). Мы не храним ваш пароль." },
    { heading:"Сторонние сервисы", body:"MovesBook использует: Firebase Authentication, Firebase Firestore, EmailJS и Vercel. Рекламные сети и трекеры не используются." },
    { heading:"Передача данных", body:"Мы не продаём, не передаём и не делимся вашими данными с третьими лицами." },
    { heading:"Хранение", body:"Локальные данные сохраняются пока вы их храните в браузере. Облачные данные сохраняются пока существует ваш аккаунт." },
    { heading:"Ваши права", body:"Вы имеете право в любой момент получить доступ, экспортировать и удалить все свои данные." },
    { heading:"Конфиденциальность несовершеннолетних", body:"MovesBook сознательно не собирает данные детей младше 13 лет." },
    { heading:"Изменения", body:"Мы можем периодически обновлять эту политику. Изменения будут отражены в дате обновления." },
    { heading:"Контакт", body:"По вопросам конфиденциальности используйте форму обратной связи в приложении." },
  ]},
  ko: { title:"개인정보 처리방침", lastUpdated:"2026년 4월", sections:[
    { heading:"소개", body:"MovesBook은 개인 브레이킹 훈련 앱입니다. 귀하의 개인정보는 소중합니다. 이 방침은 수집하는 데이터, 저장 방법 및 귀하의 권리를 설명합니다." },
    { heading:"수집하는 데이터", body:"앱에 입력하는 데이터만 수집합니다: 무브, 세트, 목표, 습관, 노트, 배틀 플랜, 스파링 세션, 캘린더 항목, 프로필 정보 및 설정.\n\n분석, 브라우징 기록, 위치 데이터 또는 기타 데이터는 수집하지 않습니다." },
    { heading:"데이터 저장 방법", body:"모든 데이터는 브라우저 localStorage를 사용하여 기기에 로컬 저장됩니다. 로그인하면 Google Firebase Firestore에 동기화됩니다." },
    { heading:"인증", body:"Firebase Authentication(Google 로그인 및 이메일/비밀번호)을 사용합니다. 비밀번호는 저장하지 않습니다." },
    { heading:"제3자 서비스", body:"MovesBook은 Firebase Authentication, Firebase Firestore, EmailJS, Vercel을 사용합니다. 광고 네트워크나 트래커는 사용하지 않습니다." },
    { heading:"데이터 공유", body:"데이터를 제3자에게 판매, 공유 또는 전송하지 않습니다." },
    { heading:"데이터 보존", body:"로컬 데이터는 브라우저에 유지되는 한 존속합니다. 클라우드 데이터는 계정이 존재하는 한 존속합니다." },
    { heading:"귀하의 권리", body:"언제든지 모든 데이터에 접근, 내보내기 및 삭제할 권리가 있습니다." },
    { heading:"미성년자 개인정보", body:"MovesBook은 13세 미만 아동의 데이터를 의도적으로 수집하지 않습니다." },
    { heading:"변경사항", body:"이 방침을 수시로 업데이트할 수 있습니다. 변경사항은 업데이트 날짜에 반영됩니다." },
    { heading:"연락처", body:"개인정보 관련 문의는 앱 내 피드백 양식을 이용해 주세요." },
  ]},
  th: { title:"นโยบายความเป็นส่วนตัว", lastUpdated:"เมษายน 2026", sections:[
    { heading:"บทนำ", body:"MovesBook เป็นแอปฝึกซ้อมเบรกกิ้งส่วนตัว ความเป็นส่วนตัวของคุณสำคัญสำหรับเรา นโยบายนี้อธิบายข้อมูลที่เราเก็บรวบรวม วิธีจัดเก็บ และสิทธิ์ของคุณ" },
    { heading:"ข้อมูลที่เราเก็บรวบรวม", body:"เราเก็บรวบรวมเฉพาะข้อมูลที่คุณป้อนในแอป: ท่า เซ็ต เป้าหมาย นิสัย บันทึก แผนแบทเทิล เซสชันสปาร์ รายการปฏิทิน ข้อมูลโปรไฟล์ และการตั้งค่า\n\nเราไม่เก็บรวบรวม analytics ประวัติการเรียกดู ข้อมูลตำแหน่ง หรือข้อมูลอื่นใด" },
    { heading:"วิธีจัดเก็บข้อมูล", body:"ข้อมูลทั้งหมดจัดเก็บในเครื่องบนอุปกรณ์ของคุณโดยใช้ localStorage ของเบราว์เซอร์ เมื่อเข้าสู่ระบบ ข้อมูลจะซิงค์กับ Google Firebase Firestore" },
    { heading:"การยืนยันตัวตน", body:"เราใช้ Firebase Authentication (เข้าสู่ระบบ Google และอีเมล/รหัสผ่าน) เราไม่เก็บรหัสผ่านของคุณ" },
    { heading:"บริการบุคคลที่สาม", body:"MovesBook ใช้: Firebase Authentication, Firebase Firestore, EmailJS และ Vercel ไม่มีเครือข่ายโฆษณาหรือตัวติดตาม" },
    { heading:"การแบ่งปันข้อมูล", body:"เราไม่ขาย แบ่งปัน หรือโอนข้อมูลของคุณให้บุคคลที่สาม" },
    { heading:"การเก็บรักษาข้อมูล", body:"ข้อมูลในเครื่องคงอยู่ตราบเท่าที่คุณเก็บไว้ในเบราว์เซอร์ ข้อมูลบนคลาวด์คงอยู่ตราบเท่าที่บัญชีของคุณมีอยู่" },
    { heading:"สิทธิ์ของคุณ", body:"คุณมีสิทธิ์เข้าถึง ส่งออก และลบข้อมูลทั้งหมดของคุณได้ตลอดเวลา" },
    { heading:"ความเป็นส่วนตัวของเด็ก", body:"MovesBook ไม่เก็บรวบรวมข้อมูลจากเด็กอายุต่ำกว่า 13 ปี โดยเจตนา" },
    { heading:"การเปลี่ยนแปลง", body:"เราอาจอัปเดตนโยบายนี้เป็นครั้งคราว การเปลี่ยนแปลงจะสะท้อนในวันที่อัปเดต" },
    { heading:"ติดต่อ", body:"สำหรับคำถามเกี่ยวกับความเป็นส่วนตัว ใช้แบบฟอร์มข้อเสนอแนะในแอป" },
  ]},
  vi: { title:"Chính Sách Bảo Mật", lastUpdated:"Tháng 4, 2026", sections:[
    { heading:"Giới thiệu", body:"MovesBook là ứng dụng luyện tập breaking cá nhân. Quyền riêng tư của bạn rất quan trọng với chúng tôi. Chính sách này giải thích dữ liệu chúng tôi thu thập, cách lưu trữ và quyền của bạn." },
    { heading:"Dữ liệu chúng tôi thu thập", body:"Chúng tôi chỉ thu thập dữ liệu bạn nhập vào ứng dụng: động tác, set, mục tiêu, thói quen, ghi chú, kế hoạch battle, phiên spar, mục lịch, thông tin hồ sơ và cài đặt.\n\nChúng tôi không thu thập phân tích, lịch sử duyệt web, dữ liệu vị trí hoặc dữ liệu khác." },
    { heading:"Cách lưu trữ dữ liệu", body:"Tất cả dữ liệu được lưu cục bộ trên thiết bị bằng localStorage của trình duyệt. Khi đăng nhập, dữ liệu được đồng bộ với Google Firebase Firestore." },
    { heading:"Xác thực", body:"Chúng tôi sử dụng Firebase Authentication (đăng nhập Google và email/mật khẩu). Chúng tôi không lưu mật khẩu của bạn." },
    { heading:"Dịch vụ bên thứ ba", body:"MovesBook sử dụng: Firebase Authentication, Firebase Firestore, EmailJS và Vercel. Không sử dụng mạng quảng cáo hay công cụ theo dõi." },
    { heading:"Chia sẻ dữ liệu", body:"Chúng tôi không bán, chia sẻ hoặc chuyển dữ liệu của bạn cho bên thứ ba." },
    { heading:"Lưu giữ dữ liệu", body:"Dữ liệu cục bộ tồn tại miễn là bạn giữ trong trình duyệt. Dữ liệu cloud tồn tại miễn là tài khoản tồn tại." },
    { heading:"Quyền của bạn", body:"Bạn có quyền truy cập, xuất và xóa tất cả dữ liệu của mình bất kỳ lúc nào." },
    { heading:"Quyền riêng tư trẻ em", body:"MovesBook không cố ý thu thập dữ liệu từ trẻ em dưới 13 tuổi." },
    { heading:"Thay đổi", body:"Chúng tôi có thể cập nhật chính sách này theo thời gian. Thay đổi sẽ phản ánh trong ngày cập nhật." },
    { heading:"Liên hệ", body:"Với câu hỏi về quyền riêng tư, hãy sử dụng biểu mẫu Phản hồi trong ứng dụng." },
  ]},
};

const terms = {
  en: {
    title: "Terms of Service",
    lastUpdated: "April 2026",
    sections: [
      { heading: "Acceptance", body: "By using MovesBook, you agree to these terms. If you do not agree, please do not use the app." },
      { heading: "Description of Service", body: "MovesBook is a personal training management tool for breaking (b-boying/b-girling). It helps you track moves, plan training, prepare for battles, and reflect on progress. The app is a mirror — it reflects your data without coaching or suggestions." },
      { heading: "User Accounts", body: "You may use MovesBook without an account (offline mode). Creating an account via Google or Email enables cloud sync. You are responsible for maintaining the security of your account credentials." },
      { heading: "User Content", body: "All content you create in MovesBook (moves, notes, goals, etc.) belongs to you. We claim no ownership over your data. You grant us only the limited right to store and sync your data as part of the service." },
      { heading: "Acceptable Use", body: "You agree to use MovesBook for its intended purpose — personal breaking training management. You agree not to:\n• Attempt to reverse-engineer, decompile, or hack the application\n• Use the service to store or transmit harmful content\n• Interfere with or disrupt the service" },
      { heading: "Premium Features", body: "Some features require a Premium subscription. Pricing and included features are displayed in the app. Subscriptions are managed through the applicable payment platform." },
      { heading: "Availability", body: "We aim to keep MovesBook available at all times, but we do not guarantee uninterrupted access. The service may be temporarily unavailable for maintenance or updates." },
      { heading: "Limitation of Liability", body: "MovesBook is provided 'as is' without warranties of any kind. We are not liable for any damages arising from your use of the app, including data loss. Always maintain your own backups." },
      { heading: "Termination", body: "You may stop using MovesBook at any time. We may suspend or terminate access if these terms are violated." },
      { heading: "Changes to Terms", body: "We may update these terms. Continued use after changes constitutes acceptance. Check back periodically for updates." },
    ]
  },
  it: { title:"Termini di Servizio", lastUpdated:"Aprile 2026", sections:[
    { heading:"Accettazione", body:"Utilizzando MovesBook, accetti questi termini. Se non sei d'accordo, ti preghiamo di non utilizzare l'app." },
    { heading:"Descrizione del Servizio", body:"MovesBook è uno strumento di gestione dell'allenamento personale per il breaking. Ti aiuta a tracciare mosse, pianificare allenamenti, prepararti per le battle e riflettere sui progressi." },
    { heading:"Account Utente", body:"Puoi usare MovesBook senza un account (modalità offline). Creare un account tramite Google o Email abilita la sincronizzazione cloud. Sei responsabile della sicurezza delle tue credenziali." },
    { heading:"Contenuti dell'Utente", body:"Tutti i contenuti che crei in MovesBook appartengono a te. Non rivendichiamo alcuna proprietà sui tuoi dati." },
    { heading:"Uso Accettabile", body:"Accetti di utilizzare MovesBook per il suo scopo previsto. Accetti di non tentare di decompilare o hackerare l'applicazione, utilizzare il servizio per contenuti dannosi o interferire con il servizio." },
    { heading:"Funzionalità Premium", body:"Alcune funzionalità richiedono un abbonamento Premium. Prezzi e funzionalità incluse sono visualizzati nell'app." },
    { heading:"Disponibilità", body:"Miriamo a mantenere MovesBook sempre disponibile, ma non garantiamo accesso ininterrotto." },
    { heading:"Limitazione di Responsabilità", body:"MovesBook è fornito 'così com'è' senza garanzie. Non siamo responsabili per danni derivanti dall'uso dell'app, inclusa la perdita di dati." },
    { heading:"Risoluzione", body:"Puoi smettere di usare MovesBook in qualsiasi momento. Possiamo sospendere l'accesso se questi termini vengono violati." },
    { heading:"Modifiche ai Termini", body:"Potremmo aggiornare questi termini. L'uso continuato dopo le modifiche costituisce accettazione." },
  ]},
  es: { title:"Términos de Servicio", lastUpdated:"Abril 2026", sections:[
    { heading:"Aceptación", body:"Al usar MovesBook, aceptas estos términos. Si no estás de acuerdo, por favor no uses la aplicación." },
    { heading:"Descripción del Servicio", body:"MovesBook es una herramienta de gestión de entrenamiento personal para breaking. Te ayuda a rastrear movimientos, planificar entrenamientos, prepararte para batallas y reflexionar sobre tu progreso." },
    { heading:"Cuentas de Usuario", body:"Puedes usar MovesBook sin cuenta (modo offline). Crear una cuenta habilita la sincronización en la nube. Eres responsable de la seguridad de tus credenciales." },
    { heading:"Contenido del Usuario", body:"Todo el contenido que creas en MovesBook te pertenece. No reclamamos propiedad sobre tus datos." },
    { heading:"Uso Aceptable", body:"Aceptas usar MovesBook para su propósito previsto. No intentes hackear la aplicación, almacenar contenido dañino o interferir con el servicio." },
    { heading:"Funciones Premium", body:"Algunas funciones requieren suscripción Premium. Los precios se muestran en la aplicación." },
    { heading:"Disponibilidad", body:"Intentamos mantener MovesBook disponible en todo momento, pero no garantizamos acceso ininterrumpido." },
    { heading:"Limitación de Responsabilidad", body:"MovesBook se proporciona 'tal cual' sin garantías. No somos responsables de daños por el uso de la app, incluyendo pérdida de datos." },
    { heading:"Terminación", body:"Puedes dejar de usar MovesBook en cualquier momento. Podemos suspender el acceso si se violan estos términos." },
    { heading:"Cambios", body:"Podemos actualizar estos términos. El uso continuado después de cambios constituye aceptación." },
  ]},
  fr: { title:"Conditions d'Utilisation", lastUpdated:"Avril 2026", sections:[
    { heading:"Acceptation", body:"En utilisant MovesBook, vous acceptez ces conditions. Si vous n'êtes pas d'accord, veuillez ne pas utiliser l'application." },
    { heading:"Description du Service", body:"MovesBook est un outil de gestion d'entraînement personnel pour le breaking. Il vous aide à suivre vos mouvements, planifier l'entraînement, préparer les battles et réfléchir à vos progrès." },
    { heading:"Comptes Utilisateur", body:"Vous pouvez utiliser MovesBook sans compte (mode hors ligne). Créer un compte active la synchronisation cloud. Vous êtes responsable de la sécurité de vos identifiants." },
    { heading:"Contenu Utilisateur", body:"Tout contenu que vous créez dans MovesBook vous appartient. Nous ne revendiquons aucune propriété sur vos données." },
    { heading:"Utilisation Acceptable", body:"Vous acceptez d'utiliser MovesBook pour son usage prévu. N'essayez pas de pirater l'application, stocker du contenu nuisible ou perturber le service." },
    { heading:"Fonctionnalités Premium", body:"Certaines fonctionnalités nécessitent un abonnement Premium. Les prix sont affichés dans l'application." },
    { heading:"Disponibilité", body:"Nous visons à maintenir MovesBook disponible en permanence, mais ne garantissons pas un accès ininterrompu." },
    { heading:"Limitation de Responsabilité", body:"MovesBook est fourni 'tel quel' sans garantie. Nous ne sommes pas responsables des dommages liés à l'utilisation de l'app." },
    { heading:"Résiliation", body:"Vous pouvez cesser d'utiliser MovesBook à tout moment. Nous pouvons suspendre l'accès en cas de violation." },
    { heading:"Modifications", body:"Nous pouvons mettre à jour ces conditions. L'utilisation continue après les changements constitue une acceptation." },
  ]},
  pt: { title:"Termos de Serviço", lastUpdated:"Abril 2026", sections:[
    { heading:"Aceitação", body:"Ao usar o MovesBook, você concorda com estes termos." },
    { heading:"Descrição do Serviço", body:"MovesBook é uma ferramenta de gestão de treino pessoal para breaking." },
    { heading:"Contas de Usuário", body:"Você pode usar o MovesBook sem conta (modo offline). Criar uma conta habilita a sincronização na nuvem." },
    { heading:"Conteúdo do Usuário", body:"Todo conteúdo que você cria no MovesBook pertence a você." },
    { heading:"Uso Aceitável", body:"Você concorda em usar o MovesBook para seu propósito pretendido. Não tente hackear o aplicativo ou interferir no serviço." },
    { heading:"Recursos Premium", body:"Alguns recursos requerem assinatura Premium. Os preços são exibidos no app." },
    { heading:"Disponibilidade", body:"Buscamos manter o MovesBook disponível, mas não garantimos acesso ininterrupto." },
    { heading:"Limitação de Responsabilidade", body:"MovesBook é fornecido 'como está' sem garantias." },
    { heading:"Rescisão", body:"Você pode parar de usar o MovesBook a qualquer momento." },
    { heading:"Alterações", body:"Podemos atualizar estes termos. O uso continuado constitui aceitação." },
  ]},
  de: { title:"Nutzungsbedingungen", lastUpdated:"April 2026", sections:[
    { heading:"Annahme", body:"Durch die Nutzung von MovesBook stimmen Sie diesen Bedingungen zu." },
    { heading:"Beschreibung", body:"MovesBook ist ein persönliches Trainingsmanagement-Tool für Breaking." },
    { heading:"Benutzerkonten", body:"Sie können MovesBook ohne Konto nutzen (Offline-Modus). Ein Konto ermöglicht Cloud-Synchronisierung." },
    { heading:"Benutzerinhalte", body:"Alle Inhalte, die Sie in MovesBook erstellen, gehören Ihnen." },
    { heading:"Akzeptable Nutzung", body:"Sie stimmen zu, MovesBook für den vorgesehenen Zweck zu nutzen." },
    { heading:"Premium-Funktionen", body:"Einige Funktionen erfordern ein Premium-Abonnement." },
    { heading:"Verfügbarkeit", body:"Wir bemühen uns um ständige Verfügbarkeit, können aber keinen unterbrechungsfreien Zugang garantieren." },
    { heading:"Haftungsbeschränkung", body:"MovesBook wird 'wie besehen' ohne Garantien bereitgestellt." },
    { heading:"Kündigung", body:"Sie können MovesBook jederzeit nicht mehr nutzen." },
    { heading:"Änderungen", body:"Wir können diese Bedingungen aktualisieren. Fortgesetzte Nutzung nach Änderungen gilt als Annahme." },
  ]},
  ja: { title:"利用規約", lastUpdated:"2026年4月", sections:[
    { heading:"同意", body:"MovesBookを使用することにより、これらの規約に同意したものとみなします。" },
    { heading:"サービスの説明", body:"MovesBookはブレイキンの個人トレーニング管理ツールです。" },
    { heading:"ユーザーアカウント", body:"アカウントなしでMovesBookを使用できます（オフラインモード）。アカウントを作成するとクラウド同期が有効になります。" },
    { heading:"ユーザーコンテンツ", body:"MovesBookで作成したすべてのコンテンツはあなたのものです。" },
    { heading:"許容される使用", body:"MovesBookを意図された目的で使用することに同意します。" },
    { heading:"プレミアム機能", body:"一部の機能にはプレミアムサブスクリプションが必要です。" },
    { heading:"可用性", body:"常時利用可能を目指していますが、中断のないアクセスを保証するものではありません。" },
    { heading:"責任の制限", body:"MovesBookは「現状のまま」保証なしで提供されます。" },
    { heading:"終了", body:"いつでもMovesBookの使用を停止できます。" },
    { heading:"規約の変更", body:"これらの規約を更新する場合があります。変更後の継続使用は同意とみなされます。" },
  ]},
  zh: { title:"服务条款", lastUpdated:"2026年4月", sections:[
    { heading:"接受", body:"使用MovesBook即表示您同意这些条款。" },
    { heading:"服务描述", body:"MovesBook是一款个人Breaking训练管理工具。" },
    { heading:"用户账户", body:"您可以在没有账户的情况下使用MovesBook（离线模式）。创建账户可启用云同步。" },
    { heading:"用户内容", body:"您在MovesBook中创建的所有内容均属于您。" },
    { heading:"可接受的使用", body:"您同意将MovesBook用于其预期目的。" },
    { heading:"高级功能", body:"某些功能需要高级订阅。" },
    { heading:"可用性", body:"我们努力保持MovesBook始终可用，但不保证不间断访问。" },
    { heading:"责任限制", body:"MovesBook按「原样」提供，不提供任何保证。" },
    { heading:"终止", body:"您可以随时停止使用MovesBook。" },
    { heading:"条款变更", body:"我们可能会更新这些条款。变更后继续使用即构成接受。" },
  ]},
  ru: { title:"Условия обслуживания", lastUpdated:"Апрель 2026", sections:[
    { heading:"Принятие", body:"Используя MovesBook, вы соглашаетесь с этими условиями." },
    { heading:"Описание сервиса", body:"MovesBook — инструмент управления персональными тренировками по брейкингу." },
    { heading:"Учётные записи", body:"Вы можете использовать MovesBook без аккаунта (офлайн-режим). Создание аккаунта включает облачную синхронизацию." },
    { heading:"Пользовательский контент", body:"Весь контент, созданный вами в MovesBook, принадлежит вам." },
    { heading:"Допустимое использование", body:"Вы соглашаетесь использовать MovesBook по назначению." },
    { heading:"Премиум-функции", body:"Некоторые функции требуют подписки Premium." },
    { heading:"Доступность", body:"Мы стремимся обеспечить постоянную доступность, но не гарантируем бесперебойный доступ." },
    { heading:"Ограничение ответственности", body:"MovesBook предоставляется «как есть» без гарантий." },
    { heading:"Прекращение", body:"Вы можете прекратить использование MovesBook в любое время." },
    { heading:"Изменения", body:"Мы можем обновить эти условия. Продолжение использования после изменений означает принятие." },
  ]},
  ko: { title:"서비스 약관", lastUpdated:"2026년 4월", sections:[
    { heading:"동의", body:"MovesBook을 사용함으로써 이 약관에 동의합니다." },
    { heading:"서비스 설명", body:"MovesBook은 브레이킹 개인 훈련 관리 도구입니다." },
    { heading:"사용자 계정", body:"계정 없이 MovesBook을 사용할 수 있습니다(오프라인 모드). 계정 생성 시 클라우드 동기화가 활성화됩니다." },
    { heading:"사용자 콘텐츠", body:"MovesBook에서 만든 모든 콘텐츠는 귀하의 소유입니다." },
    { heading:"허용되는 사용", body:"MovesBook을 의도된 목적으로 사용하는 데 동의합니다." },
    { heading:"프리미엄 기능", body:"일부 기능은 프리미엄 구독이 필요합니다." },
    { heading:"가용성", body:"항상 사용 가능하도록 노력하지만 중단 없는 접근을 보장하지 않습니다." },
    { heading:"책임 제한", body:"MovesBook은 '있는 그대로' 보증 없이 제공됩니다." },
    { heading:"종료", body:"언제든지 MovesBook 사용을 중단할 수 있습니다." },
    { heading:"변경", body:"이 약관을 업데이트할 수 있습니다. 변경 후 계속 사용하면 동의한 것으로 간주됩니다." },
  ]},
  th: { title:"เงื่อนไขการให้บริการ", lastUpdated:"เมษายน 2026", sections:[
    { heading:"การยอมรับ", body:"การใช้ MovesBook แสดงว่าคุณยอมรับเงื่อนไขเหล่านี้" },
    { heading:"คำอธิบายบริการ", body:"MovesBook เป็นเครื่องมือจัดการการฝึกซ้อมเบรกกิ้งส่วนตัว" },
    { heading:"บัญชีผู้ใช้", body:"คุณสามารถใช้ MovesBook โดยไม่มีบัญชี (โหมดออฟไลน์) การสร้างบัญชีจะเปิดใช้การซิงค์คลาวด์" },
    { heading:"เนื้อหาของผู้ใช้", body:"เนื้อหาทั้งหมดที่คุณสร้างใน MovesBook เป็นของคุณ" },
    { heading:"การใช้งานที่ยอมรับได้", body:"คุณตกลงที่จะใช้ MovesBook ตามวัตถุประสงค์ที่ตั้งใจไว้" },
    { heading:"ฟีเจอร์พรีเมียม", body:"ฟีเจอร์บางอย่างต้องการการสมัครสมาชิกพรีเมียม" },
    { heading:"ความพร้อมใช้งาน", body:"เรามุ่งมั่นให้ MovesBook พร้อมใช้งานตลอดเวลา แต่ไม่รับประกันการเข้าถึงอย่างต่อเนื่อง" },
    { heading:"การจำกัดความรับผิดชอบ", body:"MovesBook ให้บริการ 'ตามสภาพ' โดยไม่มีการรับประกัน" },
    { heading:"การยุติ", body:"คุณสามารถหยุดใช้ MovesBook ได้ตลอดเวลา" },
    { heading:"การเปลี่ยนแปลง", body:"เราอาจอัปเดตเงื่อนไขเหล่านี้ การใช้งานต่อหลังจากเปลี่ยนแปลงถือเป็นการยอมรับ" },
  ]},
  vi: { title:"Điều Khoản Dịch Vụ", lastUpdated:"Tháng 4, 2026", sections:[
    { heading:"Chấp nhận", body:"Bằng việc sử dụng MovesBook, bạn đồng ý với các điều khoản này." },
    { heading:"Mô tả dịch vụ", body:"MovesBook là công cụ quản lý luyện tập breaking cá nhân." },
    { heading:"Tài khoản người dùng", body:"Bạn có thể sử dụng MovesBook mà không cần tài khoản (chế độ ngoại tuyến). Tạo tài khoản sẽ kích hoạt đồng bộ cloud." },
    { heading:"Nội dung người dùng", body:"Tất cả nội dung bạn tạo trong MovesBook thuộc về bạn." },
    { heading:"Sử dụng chấp nhận được", body:"Bạn đồng ý sử dụng MovesBook theo mục đích dự định." },
    { heading:"Tính năng Premium", body:"Một số tính năng yêu cầu đăng ký Premium." },
    { heading:"Khả dụng", body:"Chúng tôi cố gắng duy trì MovesBook luôn sẵn sàng nhưng không đảm bảo truy cập không gián đoạn." },
    { heading:"Giới hạn trách nhiệm", body:"MovesBook được cung cấp 'nguyên trạng' không có bảo hành." },
    { heading:"Chấm dứt", body:"Bạn có thể ngừng sử dụng MovesBook bất cứ lúc nào." },
    { heading:"Thay đổi", body:"Chúng tôi có thể cập nhật các điều khoản này. Tiếp tục sử dụng sau thay đổi coi như chấp nhận." },
  ]},
};

const disclaimers = {
  en: {
    title: "Disclaimers",
    lastUpdated: "April 2026",
    sections: [
      { heading: "Not a Coach", body: "MovesBook is a data management and reflection tool. It does not provide coaching, medical advice, training programmes, or movement instruction. All content in the app is entered by you and reflects your own assessment." },
      { heading: "Physical Activity", body: "Breaking is a physically demanding activity. MovesBook does not assess your physical readiness or recommend exercises. Consult a qualified instructor or medical professional before attempting any moves or training routines. Train at your own risk." },
      { heading: "No Medical Advice", body: "The body check-in and injury tracking features are for your personal record-keeping only. They do not constitute medical diagnosis or advice. If you are injured, seek professional medical attention." },
      { heading: "Data Accuracy", body: "MovesBook reflects data you enter. We do not verify accuracy of mastery levels, move descriptions, or any other user-entered content. The app's assessments (GAP tracker, MyStance, Development Story) are based solely on your input." },
      { heading: "Third-Party Content", body: "Video links and external URLs you add to moves, goals, or notes point to third-party content. We are not responsible for the accuracy, availability, or safety of linked content." },
      { heading: "Service Availability", body: "We do not guarantee that MovesBook will be available at all times or free from errors. Data stored locally may be lost if you clear your browser storage. Always maintain backups of important data." },
      { heading: "Competition Use", body: "While MovesBook includes battle preparation and competition simulation tools, it provides no guarantees about competition outcomes. These tools are for personal planning only." },
    ]
  },
  it: { title:"Avvertenze", lastUpdated:"Aprile 2026", sections:[
    { heading:"Non è un Coach", body:"MovesBook è uno strumento di gestione dati e riflessione. Non fornisce coaching, consigli medici, programmi di allenamento o istruzioni sui movimenti." },
    { heading:"Attività Fisica", body:"Il breaking è un'attività fisicamente impegnativa. MovesBook non valuta la tua preparazione fisica. Consulta un istruttore qualificato o un professionista medico prima di tentare qualsiasi mossa. Allenati a tuo rischio." },
    { heading:"Nessun Consiglio Medico", body:"Le funzionalità di check-in corporeo e tracciamento infortuni sono solo per registrazione personale. Non costituiscono diagnosi o consulenza medica." },
    { heading:"Accuratezza dei Dati", body:"MovesBook riflette i dati che inserisci. Non verifichiamo l'accuratezza dei livelli di padronanza o altre informazioni inserite." },
    { heading:"Contenuti di Terze Parti", body:"I link video e URL esterni puntano a contenuti di terze parti. Non siamo responsabili per la loro accuratezza o sicurezza." },
    { heading:"Disponibilità del Servizio", body:"Non garantiamo che MovesBook sia sempre disponibile o privo di errori. Mantieni sempre backup dei dati importanti." },
    { heading:"Uso in Competizione", body:"Gli strumenti di preparazione alle battle non garantiscono risultati nelle competizioni. Sono solo per pianificazione personale." },
  ]},
  es: { title:"Descargos de Responsabilidad", lastUpdated:"Abril 2026", sections:[
    { heading:"No es un Entrenador", body:"MovesBook es una herramienta de gestión de datos y reflexión. No proporciona coaching, consejos médicos, programas de entrenamiento ni instrucción de movimientos." },
    { heading:"Actividad Física", body:"El breaking es una actividad físicamente exigente. MovesBook no evalúa tu preparación física. Consulta a un instructor calificado antes de intentar cualquier movimiento. Entrena bajo tu propio riesgo." },
    { heading:"Sin Consejo Médico", body:"Las funciones de check-in corporal y seguimiento de lesiones son solo para registro personal. No constituyen diagnóstico ni consejo médico." },
    { heading:"Precisión de Datos", body:"MovesBook refleja los datos que introduces. No verificamos la precisión de los niveles de dominio u otra información ingresada." },
    { heading:"Contenido de Terceros", body:"Los enlaces de video y URLs externos apuntan a contenido de terceros. No somos responsables de su precisión o seguridad." },
    { heading:"Disponibilidad", body:"No garantizamos disponibilidad constante ni ausencia de errores. Mantén siempre respaldos de datos importantes." },
    { heading:"Uso en Competición", body:"Las herramientas de preparación de batalla no garantizan resultados en competiciones." },
  ]},
  fr: { title:"Avertissements", lastUpdated:"Avril 2026", sections:[
    { heading:"Pas un Coach", body:"MovesBook est un outil de gestion de données et de réflexion. Il ne fournit pas de coaching, conseils médicaux, programmes d'entraînement ou instructions de mouvements." },
    { heading:"Activité Physique", body:"Le breaking est une activité physiquement exigeante. MovesBook n'évalue pas votre condition physique. Consultez un instructeur qualifié avant de tenter tout mouvement. Entraînez-vous à vos risques." },
    { heading:"Pas de Conseil Médical", body:"Les fonctionnalités de check-in corporel et suivi des blessures sont uniquement pour vos archives personnelles." },
    { heading:"Précision des Données", body:"MovesBook reflète les données que vous entrez. Nous ne vérifions pas la précision des informations saisies." },
    { heading:"Contenu Tiers", body:"Les liens vidéo et URLs externes pointent vers du contenu tiers. Nous n'en sommes pas responsables." },
    { heading:"Disponibilité", body:"Nous ne garantissons pas une disponibilité permanente. Maintenez toujours des sauvegardes." },
    { heading:"Usage en Compétition", body:"Les outils de préparation aux battles ne garantissent pas de résultats en compétition." },
  ]},
  pt: { title:"Avisos Legais", lastUpdated:"Abril 2026", sections:[
    { heading:"Não é um Treinador", body:"MovesBook é uma ferramenta de gestão de dados e reflexão. Não fornece coaching, aconselhamento médico ou instrução de movimentos." },
    { heading:"Atividade Física", body:"Breaking é fisicamente exigente. MovesBook não avalia sua preparação física. Consulte um profissional qualificado. Treine por sua conta e risco." },
    { heading:"Sem Aconselhamento Médico", body:"As funcionalidades de check-in corporal são apenas para registro pessoal." },
    { heading:"Precisão dos Dados", body:"MovesBook reflete os dados que você insere. Não verificamos a precisão das informações." },
    { heading:"Conteúdo de Terceiros", body:"Links de vídeo e URLs externos apontam para conteúdo de terceiros." },
    { heading:"Disponibilidade", body:"Não garantimos disponibilidade constante. Mantenha sempre backups." },
    { heading:"Uso em Competição", body:"As ferramentas de preparação de battle não garantem resultados em competições." },
  ]},
  de: { title:"Haftungsausschlüsse", lastUpdated:"April 2026", sections:[
    { heading:"Kein Coach", body:"MovesBook ist ein Datenmanagement- und Reflexions-Tool. Es bietet kein Coaching, keine medizinische Beratung oder Bewegungsanleitung." },
    { heading:"Körperliche Aktivität", body:"Breaking ist körperlich anspruchsvoll. MovesBook bewertet nicht Ihre körperliche Bereitschaft. Konsultieren Sie einen qualifizierten Trainer. Training auf eigenes Risiko." },
    { heading:"Keine medizinische Beratung", body:"Body-Check-in und Verletzungstracking-Funktionen dienen nur der persönlichen Aufzeichnung." },
    { heading:"Datengenauigkeit", body:"MovesBook spiegelt Ihre eingegebenen Daten wider. Wir überprüfen die Genauigkeit nicht." },
    { heading:"Drittanbieter-Inhalte", body:"Videolinks und externe URLs verweisen auf Drittanbieter-Inhalte." },
    { heading:"Verfügbarkeit", body:"Wir garantieren keine ständige Verfügbarkeit. Erstellen Sie immer Backups." },
    { heading:"Wettkampfnutzung", body:"Battle-Vorbereitungstools garantieren keine Wettkampfergebnisse." },
  ]},
  ja: { title:"免責事項", lastUpdated:"2026年4月", sections:[
    { heading:"コーチではありません", body:"MovesBookはデータ管理と振り返りのツールです。コーチング、医療アドバイス、トレーニングプログラム、動作指導は提供しません。" },
    { heading:"身体活動", body:"ブレイキンは身体的に厳しい活動です。MovesBookは身体の準備状態を評価しません。資格のあるインストラクターに相談してください。自己責任でトレーニングしてください。" },
    { heading:"医療アドバイスではありません", body:"ボディチェックインと怪我追跡機能は個人的な記録のためのものです。" },
    { heading:"データの正確性", body:"MovesBookはあなたが入力したデータを反映します。正確性は検証しません。" },
    { heading:"サードパーティコンテンツ", body:"動画リンクと外部URLはサードパーティコンテンツを指します。" },
    { heading:"サービスの可用性", body:"常時利用可能を保証するものではありません。重要なデータのバックアップを維持してください。" },
    { heading:"競技での使用", body:"バトル準備ツールは競技結果を保証しません。" },
  ]},
  zh: { title:"免责声明", lastUpdated:"2026年4月", sections:[
    { heading:"非教练", body:"MovesBook是数据管理和反思工具。不提供教练指导、医疗建议、训练计划或动作教学。" },
    { heading:"体力活动", body:"Breaking是高强度体力活动。MovesBook不评估您的身体准备状态。请咨询专业教练。自行承担训练风险。" },
    { heading:"非医疗建议", body:"身体检查和伤病追踪功能仅供个人记录使用。" },
    { heading:"数据准确性", body:"MovesBook反映您输入的数据。我们不验证其准确性。" },
    { heading:"第三方内容", body:"视频链接和外部URL指向第三方内容。" },
    { heading:"服务可用性", body:"不保证始终可用。请始终备份重要数据。" },
    { heading:"比赛使用", body:"Battle准备工具不保证比赛结果。" },
  ]},
  ru: { title:"Отказ от ответственности", lastUpdated:"Апрель 2026", sections:[
    { heading:"Не тренер", body:"MovesBook — инструмент управления данными и рефлексии. Не предоставляет коучинг, медицинские советы или инструкции по движениям." },
    { heading:"Физическая активность", body:"Брейкинг — физически требовательная активность. MovesBook не оценивает вашу физическую готовность. Консультируйтесь с квалифицированным инструктором. Тренируйтесь на свой риск." },
    { heading:"Не медицинский совет", body:"Функции проверки тела и отслеживания травм предназначены только для личных записей." },
    { heading:"Точность данных", body:"MovesBook отражает введённые вами данные. Мы не проверяем их точность." },
    { heading:"Сторонний контент", body:"Видеоссылки и внешние URL указывают на сторонний контент." },
    { heading:"Доступность", body:"Не гарантируем постоянную доступность. Всегда делайте резервные копии." },
    { heading:"Использование на соревнованиях", body:"Инструменты подготовки к батлам не гарантируют результатов на соревнованиях." },
  ]},
  ko: { title:"면책 조항", lastUpdated:"2026년 4월", sections:[
    { heading:"코치가 아닙니다", body:"MovesBook은 데이터 관리 및 성찰 도구입니다. 코칭, 의료 조언, 훈련 프로그램 또는 동작 지도를 제공하지 않습니다." },
    { heading:"신체 활동", body:"브레이킹은 신체적으로 힘든 활동입니다. MovesBook은 신체적 준비 상태를 평가하지 않습니다. 자격을 갖춘 강사에게 문의하세요. 자기 책임하에 훈련하세요." },
    { heading:"의료 조언 아님", body:"바디 체크인과 부상 추적 기능은 개인 기록용입니다." },
    { heading:"데이터 정확성", body:"MovesBook은 입력한 데이터를 반영합니다. 정확성을 검증하지 않습니다." },
    { heading:"제3자 콘텐츠", body:"동영상 링크와 외부 URL은 제3자 콘텐츠를 가리킵니다." },
    { heading:"서비스 가용성", body:"항상 사용 가능함을 보장하지 않습니다. 항상 백업을 유지하세요." },
    { heading:"대회 사용", body:"배틀 준비 도구는 대회 결과를 보장하지 않습니다." },
  ]},
  th: { title:"ข้อจำกัดความรับผิดชอบ", lastUpdated:"เมษายน 2026", sections:[
    { heading:"ไม่ใช่โค้ช", body:"MovesBook เป็นเครื่องมือจัดการข้อมูลและไตร่ตรอง ไม่ให้คำแนะนำการฝึก คำแนะนำทางการแพทย์ หรือการสอนท่า" },
    { heading:"กิจกรรมทางกาย", body:"เบรกกิ้งเป็นกิจกรรมที่ต้องใช้ร่างกายมาก MovesBook ไม่ประเมินความพร้อมทางกายของคุณ ปรึกษาผู้ฝึกสอนที่มีคุณสมบัติ ฝึกซ้อมด้วยความเสี่ยงของคุณเอง" },
    { heading:"ไม่ใช่คำแนะนำทางการแพทย์", body:"ฟีเจอร์เช็คอินร่างกายและติดตามอาการบาดเจ็บมีไว้สำหรับบันทึกส่วนตัวเท่านั้น" },
    { heading:"ความถูกต้องของข้อมูล", body:"MovesBook สะท้อนข้อมูลที่คุณป้อน เราไม่ตรวจสอบความถูกต้อง" },
    { heading:"เนื้อหาบุคคลที่สาม", body:"ลิงก์วิดีโอและ URL ภายนอกชี้ไปยังเนื้อหาของบุคคลที่สาม" },
    { heading:"ความพร้อมใช้งาน", body:"เราไม่รับประกันความพร้อมใช้งานตลอดเวลา สำรองข้อมูลเสมอ" },
    { heading:"การใช้ในการแข่งขัน", body:"เครื่องมือเตรียมแบทเทิลไม่รับประกันผลการแข่งขัน" },
  ]},
  vi: { title:"Tuyên Bố Miễn Trừ", lastUpdated:"Tháng 4, 2026", sections:[
    { heading:"Không phải huấn luyện viên", body:"MovesBook là công cụ quản lý dữ liệu và suy ngẫm. Không cung cấp huấn luyện, lời khuyên y tế hoặc hướng dẫn động tác." },
    { heading:"Hoạt động thể chất", body:"Breaking là hoạt động thể chất đòi hỏi cao. MovesBook không đánh giá sự sẵn sàng thể chất của bạn. Hãy tham khảo huấn luyện viên có trình độ. Tập luyện tự chịu rủi ro." },
    { heading:"Không phải lời khuyên y tế", body:"Tính năng check-in cơ thể và theo dõi chấn thương chỉ dành cho ghi chép cá nhân." },
    { heading:"Độ chính xác dữ liệu", body:"MovesBook phản ánh dữ liệu bạn nhập. Chúng tôi không xác minh độ chính xác." },
    { heading:"Nội dung bên thứ ba", body:"Liên kết video và URL bên ngoài trỏ đến nội dung bên thứ ba." },
    { heading:"Khả dụng dịch vụ", body:"Không đảm bảo luôn khả dụng. Luôn sao lưu dữ liệu quan trọng." },
    { heading:"Sử dụng trong thi đấu", body:"Công cụ chuẩn bị battle không đảm bảo kết quả thi đấu." },
  ]},
};

// Build the unified LEGAL_CONTENT object
const LANGS = ["en","it","es","fr","pt","de","ja","zh","ru","ko","th","vi"];
export const LEGAL_CONTENT = {};
LANGS.forEach(lang => {
  LEGAL_CONTENT[lang] = {
    privacy: privacy[lang],
    terms: terms[lang],
    disclaimers: disclaimers[lang],
  };
});
